
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: 858140858140

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
