# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c13a24785274a244342a3ccdc4f07b90addf2c0926fce9be87241dc28ed299e6b1db4af6483c36928ea7b248463475a1558249211649a05c35ea91574baa8f8a

test:
  secret_key_base: 64c172a0d0d19c4b209ae3a729a8f5cc07c262b3cd0d41d99edb003524ccb913515e830b9805cdcb7cd4258943ddd5b044aeea786ff912964015119a675fa6ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
